language: ruby
env:
  - SSHUSER=travis
rvm:
  - 2.1.2
  - 2.3.0
before_install: 
  - sudo apt-get -qq update
  - sudo apt-get install sshpass
  - ps ax | grep ssh
  - ls -la $HOME/.ssh
  - gem install bundler
addons:
  ssh_known_hosts:
    - localhost
